# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Legitify < Formula
  desc ""
  homepage "https://github.com/Legit-Labs/legitify"
  version "0.2.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Legit-Labs/legitify/releases/download/v0.2.5/legitify_0.2.5_darwin_arm64.tar.gz"
      sha256 "2dd22b13294a99b299215d534f47b6e0250e27e5e7f9fddd5dc67f55fa9f98d8"

      def install
        bin.install "legitify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Legit-Labs/legitify/releases/download/v0.2.5/legitify_0.2.5_darwin_amd64.tar.gz"
      sha256 "b280a464a79149bdf7d17be295673350e985237abe4315ba35a3fb754a09093d"

      def install
        bin.install "legitify"
      end
    end
  end
end
