# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Legitify < Formula
  desc "Legitify - open source scm scanning tool by Legit Security"
  homepage "https://github.com/Legit-Labs/legitify"

  on_macos do
    
    url "https://github.com/legit-labs/legitify/releases/download/v0.2.5/legitify_0.2.5_darwin_amd64.tar.gz"
    sha256 "43a9e9d94c6908ed6a47a83a19b4cc430fefcf6a8e55c4b199a8bd93ae4aeee9"
    version "v0.2.5"

    def install
      bin.install "legitify"
    end
  end
end
