# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Legitify < Formula
  desc "Legitify - open source scm scanning tool by Legit Security"
  homepage "https://github.com/Legit-Labs/legitify"

  on_macos do
    
    url "https://github.com/legit-labs/legitify/releases/download/v0.2.6/legitify_0.2.6_darwin_amd64.tar.gz"
    sha256 "ca6344c3ea9fa3bf18f300fa600e79a58c2e1a010e022245743c0c7dc525647f"
    version "v0.2.6"

    def install
      bin.install "legitify"
    end
  end
end
